import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function load(name){const ctx=vm.createContext({DATA:{},state:{profile:{},packTripId:'GENERAL'},document:{addEventListener(){},readyState:'loading'},setTimeout(){},fishStorage:{getItem(){return null}},crypto:{randomUUID:()=>String(++ctx.uuid)},uuid:0,tripStatus:t=>t.status||'Upcoming'});ctx.window=ctx;ctx.render=()=>{};ctx.side=()=>{};let code=fs.readFileSync(new URL('../assets/'+name,import.meta.url),'utf8');if(name.includes('packing'))code=code.replace('normalize,locked,active,weight','normalize,locked,active,weight,assign');vm.runInContext(code,ctx);return ctx}
test('general legacy arrays preserve items and zero quantity/weight',()=>{const c=load('fishos-packing-v64.js');c.state.packing=[{name:'Sample',qty:0,weight:0}];const p=c.fishosPacking64.active();assert.equal(p.items.FIELD[0].qty,0);assert.equal(c.fishosPacking64.weight(p.items.FIELD[0]),0)});
test('completed trip cannot be overwritten by packing mutations',()=>{const c=load('fishos-packing-v64.js');c.DATA.trips=[{id:'Past',status:'Completed'}];c.state.packingByTrip={Past:{FIELD:[{name:'Preserved'}]}};assert.throws(()=>c.fishosPacking64.assign('Past',{FIELD:[]}),/locked/);assert.equal(c.state.packingByTrip.Past.FIELD[0].name,'Preserved')});
test('named linked list and trip are independent snapshots',()=>{const c=load('fishos-packing-v64.js');c.DATA.trips=[{id:'Future',status:'Upcoming'}];c.DATA.field_settings={pack_lists:{one:{name:'Named',linked_trip:'Future',items:{FIELD:[]}}}};c.fishosPacking64.assign('Future',{FIELD:[{name:'Sample'}]});c.state.packingByTrip.Future.FIELD[0].name='Changed';assert.equal(c.DATA.field_settings.pack_lists.one.items.FIELD[0].name,'Sample')});
test('journal evidence does not count until confirmed; confirmation is idempotent and linked',()=>{const c=load('fishos-journal-catches-v64.js');c.DATA.journal=[{title:'Synthetic',date:'2026-01-01',species:['Trout'],observed:'Landed a 22 inch trout.'}];const f=c.fishosCatches64.findings()[0];assert.equal(c.DATA.fish,undefined);assert.equal(f.length,22);c.fishosCatches64.confirm(f,'Trout',22);c.fishosCatches64.confirm(f,'Trout',22);assert.equal(c.DATA.fish.length,1);assert.equal(c.DATA.fish[0].source_journal_id,c.DATA.journal[0].id);assert.equal(c.fishosCatches64.findings().length,0)});
test('research mentions can be dismissed and invalid species/length cannot become catches',()=>{const c=load('fishos-journal-catches-v64.js');c.DATA.journal=[{title:'Synthetic',notes:'Saw a 30 inch fish.'}];const f=c.fishosCatches64.findings()[0];assert.throws(()=>c.fishosCatches64.confirm(f,'',30),/species/);assert.throws(()=>c.fishosCatches64.confirm(f,'Trout',-1),/length/);c.DATA.field_settings={journal_review:{[f.sourceKey]:'dismissed'}};assert.equal(c.fishosCatches64.findings().length,0)});
test('fishing and travel estimates have separate basis and exclude unknown coordinates/dates',()=>{const c=load('fishos-maintenance-v64.js');c.DATA.field_settings={distance_settings:{fishing_miles_per_day:2,origins:[{from_year:2020,to_year:2022,lat:40,lon:-100},{from_year:2023,to_year:9999,lat:45,lon:-120}]}};c.DATA.trips=[{status:'Completed',date:'2021-01-01–2021-01-03',lat:41,lon:-100},{status:'Completed',date:'2025-01-01',lat:46,lon:-120},{status:'Historical',date:'2018'}];const v=c.fishosMaintenance64.distanceStats();assert.equal(v.fishingEstimated,8);assert.equal(v.covered,2);assert.ok(v.travelEstimated>270&&v.travelEstimated<280);assert.equal(c.fishosMaintenance64.coord({lat:'',lon:''}),null);assert.equal(c.fishosMaintenance64.days({date:'2018'}),0)});
