import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function load(){const c=vm.createContext({DATA:{},state:{profile:{}},document:{readyState:'loading',addEventListener(){}},crypto:{randomUUID:()=>String(++c.next)},next:0,localISO:d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),fishStorage:{getItem(){return null}},persistData(){},side(){},render(){}});c.window=c;vm.runInContext(fs.readFileSync(new URL('../assets/fishos-cleanup-v1-065.js',import.meta.url),'utf8'),c);return c}
test('past date ranges override stale Upcoming labels and lock packing',()=>{const c=load(),t={date:'Aug 8–15, 2026',status:'Upcoming'};assert.equal(c.tripStatus(t,new Date('2026-10-09T12:00:00')),'Completed');assert.equal(c.fishosCleanup65.tripDates(t).end,'2026-08-15');assert.equal(c.tripStatus({date:'2026-08-08–2026-08-15',status:'Planned / booked'},new Date('2026-10-09T12:00:00')),'Completed');assert.equal(c.fishosCleanup65.tripDates({date:'2018'}),null);assert.equal(c.tripStatus({...t,status:'Cancelled'}),'Cancelled')});
test('physical ounces never parse reel line classification as weight',()=>{const c=load();assert.equal(c.fishosCleanup65.measuredWeight({weight:'8/9/10wt'},'reels'),null);assert.equal(c.fishosCleanup65.measuredWeight({weight:'5/6wt',weight_oz:7.5},'reels'),7.5);assert.equal(c.fishosCleanup65.measuredWeight({weight_oz:0},'packs'),0);assert.equal(c.fishosCleanup65.measuredWeight({weight:12},'packs'),12)});
test('owner tools require signed-in owner identity',()=>{const c=load();assert.equal(c.fishosCleanup65.owner(),false);c.state.profile={loggedIn:true,userId:'other'};assert.equal(c.fishosCleanup65.owner(),false);c.state.profile.owner=true;assert.equal(c.fishosCleanup65.owner(),true);c.state.profile.loggedIn=false;assert.equal(c.fishosCleanup65.owner(),false)});
test('automatic journal catches exclude sightings and girth, deduplicate repeated entries, retain edits',()=>{const c=load(),j={title:'Synthetic',date:'2026-01-01',species:['Summer steelhead'],observed:'Produced a 29 in steelhead with 14.5 in girth. Saw a 30 inch steelhead.'};c.DATA.journal=[j,{...j}];assert.equal(c.fishosCleanup65.autoCatches(),1);assert.equal(c.DATA.fish[0].length_inches,29);assert.ok(c.DATA.fish[0].source_journal_id);c.DATA.fish[0].length_inches=28;assert.equal(c.fishosCleanup65.autoCatches(),0);assert.equal(c.DATA.fish[0].length_inches,28)});
test('brown catch estimate is distinct from observed sizes and rainbow inference',()=>{const c=load();c.DATA.journal=[{title:'Synthetic',species:['Brown trout','Rainbow trout'],observed:'Many 12–22 inch browns farther out.',result:'A 24+ inch brown and a similarly large rainbow were caught.'}];assert.equal(c.fishosCleanup65.autoCatches(),1);assert.equal(c.DATA.fish[0].species,'Brown trout');assert.equal(c.DATA.fish[0].measurement_accuracy,'estimate')});
test('distinct reported catches in one entry survive; negated catches do not count',()=>{const c=load();c.DATA.journal=[{title:'Synthetic',species:['Trout'],observed:'Landed 22 inch and 24 inch trout. Never caught a 30 inch trout.'}];assert.equal(c.fishosCleanup65.autoCatches(),2);assert.deepEqual(Array.from(c.DATA.fish,x=>x.length_inches),[22,24])});
