import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../assets/fishos-workspace-v1-066.js',import.meta.url),'utf8');
function setup(){const c=vm.createContext({DATA:{rods:[],component_gear:{},section_notes:[]},state:{page:'home',profile:{}},document:{readyState:'loading'},window:null,fishStorage:{getItem:()=>null},render(){},side(){},crypto:{randomUUID:()=> 'synthetic'},slug:x=>x,confirm:()=>false});c.window=c;vm.runInContext(source.replace('window.fishosWorkspace66={','window.testFilter=v=>filter=v;window.testSort=v=>sort=v;window.testSearch=v=>search=v;window.fishosWorkspace66={'),c);return c}
test('category filters restore all rows after switching repeatedly; sorting preserves editor indexes',()=>{const c=setup();c.DATA.component_gear={reels:[{name:'Z Reel',cost:100},{name:'A Reel',cost:300}],packs:[{name:'Pack',cost:20}]};c.testFilter('reels');assert.equal(c.fishosWorkspace66.visibleRows().length,2);c.testFilter('packs');assert.equal(c.fishosWorkspace66.visibleRows().length,1);c.testFilter('all');c.testSort('value');assert.deepEqual(Array.from(c.fishosWorkspace66.visibleRows(),r=>[r.name,r.index]),[['A Reel',1],['Z Reel',0],['Pack',0]]);c.testSearch('missing');assert.equal(c.fishosWorkspace66.visibleRows().length,0);c.testSearch('');assert.equal(c.fishosWorkspace66.visibleRows().length,3)});
test('classes remain separate from mass and legacy rod prices use correct column',()=>{const c=setup();c.DATA.rods=[['X','6','Brand','Model','','','','',900]];c.DATA.component_gear={reels:[{name:'Reel',line_class:'8/9/10 wt',weight_oz:7.5,cost:200}]};assert.equal(c.fishosWorkspace66.rows()[0].cost,900);assert.deepEqual(Array.from(c.fishosWorkspace66.classNumbers('9/10wt',12)),[9,10]);assert.deepEqual(Array.from(c.fishosWorkspace66.classNumbers('15wt',12)),[])});
test('classification rejects malformed and partly out-of-range labels',()=>{const c=setup();assert.equal(c.fishosWorkspace66.validClass('5/6 wt',12,true),true);assert.equal(c.fishosWorkspace66.validClass('7+ wt',15,false),true);assert.equal(c.fishosWorkspace66.validClass('5/16 wt',15,true),false);assert.equal(c.fishosWorkspace66.validClass('5 wt nonsense',15,false),false);assert.equal(c.fishosWorkspace66.validClass('5/6 wt',15,false),false)});
test('deleting a rod shifts its indexed specs, photos and health; snapshots remain intact',()=>{const c=setup();c.DATA.rods=[['A'],['B'],['C']];c.DATA.field_settings={gear_specs:{'rods|0':{weight_oz:1},'rods|1':{weight_oz:2},'rods|2':{weight_oz:3}},gear_health:{'rods|2|c':{condition:'Good'}}};c.DATA.rod_photos={0:'A',1:'B',2:'C'};c.DATA.packingByTrip={past:{name:'B'}};c.fishosWorkspace66.removeAt('rods',1);assert.equal(c.DATA.rods[1][0],'C');assert.equal(c.DATA.field_settings.gear_specs['rods|1'].weight_oz,3);assert.equal(c.DATA.rod_photos[1],'C');assert.equal(c.DATA.packingByTrip.past.name,'B');assert.equal(c.DATA.field_settings.gear_health['rods|1|c'].condition,'Good')});
test('gear metadata survives category moves and rod renames without stale keys',()=>{const c=setup(),gear={id:'gear63-one',name:'Pack',custom:{keep:true}};c.DATA.field_settings={gear_health:{'packs|gear63-one':{condition:'Fair',last_serviced:'2026-01-02',notes:'Keep me'}},gear_brands:{'packs|gear63-one':'Brand A'}};const carried=c.fishosWorkspace66.takeGearMetadata('packs',0,gear);const moved={...gear,name:'Net'};c.fishosWorkspace66.putGearMetadata('nets',0,moved,{...moved,brand:'Brand B',condition:'Good'},carried);assert.equal(c.DATA.field_settings.gear_health['packs|gear63-one'],undefined);const health=c.DATA.field_settings.gear_health['nets|gear63-one'];assert.equal(health.condition,'Good');assert.equal(health.last_serviced,'2026-01-02');assert.equal(health.notes,'Keep me');assert.equal(health.brand,'Brand B');assert.equal(c.DATA.field_settings.gear_brands['nets|gear63-one'],'Brand B');const rod=['Old','5','Rod Brand'];c.DATA.field_settings.gear_health['rods|0|old-5-rod-brand']={condition:'Fair',next_review:'2027-01-01'};const rodMeta=c.fishosWorkspace66.takeGearMetadata('rods',0,rod);rod[0]='New';c.fishosWorkspace66.putGearMetadata('rods',0,rod,{brand:'Rod Brand',condition:'Excellent'},rodMeta);assert.equal(c.DATA.field_settings.gear_health['rods|0|old-5-rod-brand'],undefined);assert.equal(c.DATA.field_settings.gear_health['rods|0|new-5-rod-brand'].next_review,'2027-01-01')});
test('trip map links use selected trip coordinates and research is matched by trip name',()=>{const c=setup();const t={id:'Katmai 2026',place:'Katmai',lat:58.73,lon:-156.99};assert.match(c.fishosWorkspace66.tripMaps(t)[0][1],/58.73%2C-156.99/);c.DATA.section_notes=[{title:'Katmai lodge',body:'notes'},{title:'Other',body:'different'}];assert.equal(c.fishosWorkspace66.tripResearch(t).length,1)});
test('account changes and hydration block inventory mutations',()=>{const c=setup();c.state.profile={loggedIn:true,userId:'A'};assert.throws(()=>c.fishosWorkspace66.guard('A'),/loading/);c.state.privateHydrated=true;assert.doesNotThrow(()=>c.fishosWorkspace66.guard('A'));assert.throws(()=>c.fishosWorkspace66.guard('B'),/Account changed/)});
